### ISSUE TITLE
update version on npm

### ISSUE THREAD

**Issue by ojczeo** [YuChenLi923/vue-scroll-bar#4]
@YuChenLi923 could you update version of package on `npm`?
HOW TO:
https://docs.npmjs.com/getting-started/publishing-npm-packages#updating-your-package

> How To Update the Version Number
> When you make changes, you can update the package using
> 
> npm version <update_type>
> 
> where <update_type> is one of the semantic versioning release types, patch, minor, or major.
> 
> This command will change the version number in package.json.
> 
> Note: this will also add a tag with the updated release number to your git repository if you have linked one to your npm account.
> 
> After updating the version number, run npm publish again.
> 
> Test: Go to https://npmjs.com/package/<package>. The package number should be updated.

**Comment by YuChenLi923** [comment]
Thank you for reminding me.Previously I modified the version in package.json.
