### ISSUE TITLE
recalculate() is little bit buggy for reactive content

### ISSUE THREAD

**Issue by ojczeo** [YuChenLi923/vue-scroll-bar#7]
@YuChenLi923 
When content items are removed one by one and content is scrolled to end, recalculation of scrollbars is going wrong - screencast below:
![klh20jcm38](https://user-images.githubusercontent.com/1917131/37242906-48107dfa-2471-11e8-9f2b-4e33ec01776d.gif)
 
It's a little hard bit for me to understand how the recalculate working, could you fix that, please? :)

**Comment by YuChenLi923** [comment]
I've fixed it in the latest version.

**Comment by YuChenLi923** [comment]
抱歉，最近去实习了，没看到哈，麻烦发一下你的打包配置，可能是loader那里配错了

**Comment by YuChenLi923** [comment]
@coderew 抱歉，最近去实习了，没看到哈，麻烦发一下你的打包配置，可能是loader那里配错了

**Comment by SpringServer** [comment]
how to watch scroll
